config/routes.rb
Rails.application.routes.draw do


# 顧客用
# URL /customers/sign_in ...

devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# # 管理者用
# # URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :designs, only: [:new, :create, :show, :edit, :update, :index, :destroy]
    resources :items, only: [:create]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :update]
    resources :orders, only: [:show, :update]
    resources :reviews, only: [:index, :destroy]
    get '/' => 'homes#top'
  end

  root to: "public/homes#top"
  scope module: :public do
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    get '/customers/my_page', to: 'customers#show'
    get '/customers/my_page/edit', to: 'customers#edit'
    patch '/customers/my_page', to: 'customers#update'
    resources :designs, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy, :destroy_all]
    post '/cart_items/order_made_create' => 'cart_items#order_made_create'
    delete :cart_items, to: 'cart_items#destroy_all'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks'=> 'orders#thanks'
    resources :orders, only: [:new, :index, :show, :create]
    resources :reviews, only: [:index, :new, :create]
  end
end


#new_admin_session GET    /admin/sign_in(.:format)                        admin/sessions#new
#admin_session POST   /admin/sign_in(.:format)                            admin/sessions#create
#destroy_admin_session DELETE /admin/sign_out(.:format)                   admin/sessions#destroy

#admin GET    /admin(.:format)                                              admin/homes#top

#admin_designs GET    /admin/designs(.:format)                             admin/designs#index
#              POST   /admin/designs(.:format)                             admin/designs#create
#new_admin_design GET    /admin/designs/new(.:format)                      admin/designs#new
#edit_admin_design GET    /admin/designs/:id/edit(.:format)                admin/designs#edit
#admin_design GET    /admin/designs/:id(.:format)                          admin/designs#show
#             PATCH  /admin/designs/:id(.:format)                          admin/designs#update
#             DELETE /admin/designs/:id(.:format)                          admin/designs#destroy

#admin_items POST   /admin/items(.:format)                                 admin/items#create

#admin_genres GET    /admin/genres(.:format)                                admin/genres#index
#             POST   /admin/genres(.:format)                                admin/genres#create
#edit_admin_genre GET    /admin/genres/:id/edit(.:format)                   admin/genres#edit
#admin_genre PATCH  /admin/genres/:id(.:format)                             admin/genres#update

#admin_customers GET    /admin/customers(.:format)                          admin/customers#index
#edit_admin_customer GET    /admin/customers/:id/edit(.:format)             admin/customers#edit
#admin_customer GET    /admin/customers/:id(.:format)                       admin/customers#show
#               PATCH  /admin/customers/:id(.:format)                       admin/customers#update

#admin_order GET    /admin/orders/:id(.:format)                             admin/orders#show
#PATCH  /admin/orders/:id(.:format)                                         admin/orders#update

#admin_reviews GET    /admin/reviews(.:format)                              admin/reviews#index
#admin_review DELETE /admin/reviews/:id(.:format)                           admin/reviews#destroy


#new_customer_password GET    /customers/password/new(.:format)             devise/passwords#new
#edit_customer_password GET    /customers/password/edit(.:format)           devise/passwords#edit

#new_customer_registration GET    /customers/sign_up(.:format)              public/registrations#new
#edit_customer_registration GET    /customers/edit(.:format)                public/registrations#edit



#new_customer_session GET    /customers/sign_in(.:format)                   public/sessions#new
#customer_session POST   /customers/sign_in(.:format)                       public/sessions#create
#destroy_customer_session DELETE /customers/sign_out(.:format)              public/sessions#destroy

#genres GET    /genres(.:format)                                            public/genres#index

#designs GET    /designs(.:format)                                          public/designs#index
#design GET    /designs/:id(.:format)                                       public/designs#show

#customers_unsubscribe GET    /customers/unsubscribe(.:format)              public/customers#unsubscribe
#customers_my_page GET    /customers/my_page(.:format)                      public/customers#show
#customers_my_page_edit GET    /customers/my_page/edit(.:format)            public/customers#edit
#                       PATCH  /customers/my_page(.:format)                 public/customers#update
#customers_withdraw PATCH  /customers/withdraw(.:format)                    public/customers#withdraw

#cart_items GET    /cart_items(.:format)                                    public/cart_items#index
#           POST   /cart_items(.:format)                                    public/cart_items#create
#cart_items_order_made_create POST   /cart_items/order_made_create(.:format)    public/cart_items#order_made_create

#cart_item PATCH  /cart_items/:id(.:format)                                 public/cart_items#update
#          DELETE /cart_items/:id(.:format)                                 public/cart_items#destroy
#          DELETE /cart_items(.:format)                                     public/cart_items#destroy_all

#orders GET    /orders(.:format)                                            public/orders#index
#POST   /orders(.:format)                                                   public/orders#create
#new_order GET    /orders/new(.:format)                                     public/orders#new
#order GET    /orders/:id(.:format)                                         public/orders#show
#orders_confirm POST   /orders/confirm(.:format)                            public/orders#confirm
#orders_thanks GET    /orders/thanks(.:format)                              public/orders#thanks

#address_index POST   /address(.:format)                                    public/address#create

#reviews GET    /reviews(.:format)                                          public/reviews#index
#        POST   /reviews(.:format)                                          public/reviews#create
#new_review GET    /reviews/new(.:format)                                   public/reviews#new

#new_customer_password GET    /customers/password/new(.:format)             devise/passwords#new
#edit_customer_password GET    /customers/password/edit(.:format)           devise/passwords#edit
#customer_password PATCH  /customers/password(.:format)                     devise/passwords#update
#PUT    /customers/password(.:format)                                       devise/passwords#update
#POST   /customers/password(.:format)                                       devise/passwords#create

app/models/design.rb
class Design < ApplicationRecord

  belongs_to :genre
  has_many :items, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many_attached :images

  # reject_ifは、入力フォームを追加しているもののすべてが空白の場合にリジェクトする
  # allow_destroyは、入力フォームでこのオブジェクトが削除された際に削除を許可する
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

    ## 消費税を求めるメソッド
  def with_tax_price
    (design_price*1.1).floor##(floorは端数切り捨てメソッド)
  end

end

app/controllers/admin/designs_controller.rb
class Admin::DesignsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @designs = Design.all.order("created_at DESC")
  end

  def new
    @design = Design.new
    item = @design.items.build
  end

  def create
    @design = Design.new(design_params)
    if @design.save
      redirect_to admin_designs_path
    else
      redirect_to admin_genres_path
    end
  end

  def show
    @design = Design.find(params[:id])
    @items = @design.items.all
  end

  def edit
    @design = Design.find(params[:id])
    @items = @design.items.all
  end

  def update
    @design= Design.find(params[:id])

    if params[:design][:image_ids].present?
      params[:design][:image_ids].each do |image_id|
        image = @design.images.find(image_id)
        image.purge
      end
    end

    if @design.update(design_params)
      # redirect_to admin_design_path(@design.id)
      redirect_to admin_designs_path
    else
      redirect_to admin_genres_path
    end
  end

  def destroy
    @design = Design.find(params[:id])
    @design.destroy
    redirect_to admin_designs_path
  end


  private

  def design_params
    params.require(:design).permit(
      :genre_id,
      :design_name,
      :design_introduction,
      :design_price,
      :design_type,
      images: [],
      items_attributes: [:id, :image, :design_id, :item_price, :stock, :is_active, :item_introduction, :clone, :_destroy]
      )
  end

end

app/helpers/admin/designs_helper.rb
module Admin::DesignsHelper
end

app/views/admin/designs/_item-form-edit.html.erb
<div class="nested-fields"><!--nested-fieldsはフォーム削除に必要-->

  <div class="item-content">

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="item[image]">通常商品画像</label></div>
      <div class="col-auto"><%= item.file_field :image, accept: "image/*" %></div><br>
    </div>

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="item[item_introduction]">商品説明</label></div>
      <div class="col-auto"><%= item.text_area :item_introduction, required: true %></div>
    </div>
    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="item[item_price]">税抜価格</label></div>
        <div class="col-auto"><%= item.text_field :item_price, required: true %></div>
    </div>
    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="item[stock]">在庫数</label></div>
      <div class="col-auto"><%= item.number_field :stock ,min: 0, max:10, required: true %></div>
    </div>

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"></div>
      <%= item.radio_button :is_active, true %>
      <%= item.label :is_active, "販売中", {value: true, style: "display: inline-block;"} %>
      <%= item.radio_button :is_active, false %>
      <%= item.label :is_active, "販売停止中", {value: false, style: "display: inline-block;"} %>
    </div>
    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"></div>
      <%= link_to_remove_association "削除", item, class: "btn btn-danger px-4 mb-3" %>
    </div>

  </div>

</div>

app/views/admin/designs/_item-form.html.erb
<div class="nested-fields"><!--nested-fieldsはフォーム削除に必要-->

  <div class="item-content">

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="item[image]">通常商品画像追加</label></div>
      <div class="col-auto"><%= item.file_field :image, accept: "image/*" %></div><br>
    </div>

    <div class="row">
      <div class="col-md-2 col-sm-3"></div>
      <div class="col-auto font-weight-bold text-danger">※オーダーメイド商品の場合は画像追加ナシ</div><br>
    </div>

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="item[item_introduction]">商品説明</label></div>
      <div class="col-auto"><%= item.text_area :item_introduction, required: true %></div>
    </div>

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="item[item_price]">税抜価格</label></div>
        <div class="col-auto"><%= item.text_field :item_price, required: true %></div>
    </div>

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="item[stock]">在庫数</label></div>
      <div class="col-auto"><%= item.number_field :stock ,min: 0, max:10, required: true %></div>
    </div>

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"></div>
      <%= item.radio_button :is_active, true, checked: true %>
      <%= item.label :is_active, "販売中", {value: true, style: "display: inline-block;"} %>
      <%= item.radio_button :is_active, false, checked: false %>
      <%= item.label :is_active, "販売停止中", {value: false, style: "display: inline-block;"} %>
    </div>

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"></div>
      <%= link_to_remove_association "削除", item, class: "btn btn-danger px-4 mb-3" %>
    </div>

  </div>

</div>

app/views/admin/designs/edit.html.erb
<%= render 'layouts/admin-header' %>

<%= form_with model: @design, url: admin_design_path, method: :patch do |f| %>
  <div class="container">

    <h3 class="mb-3 mt-3">デザイン編集</h3>

    <h4 class="mb-3 mt-3 font-weight-bold border-bottom">デザイン</h4>
    <article>
      <label for="images">画像追加</label>
      <%= f.file_field :images, accept: "image/*", multiple: true, class: "mb-2" %>
      <output id="result" />
      <% @design.images.each do |image| %>

        <!--multiple: true＝複数の選択を可能にする-->
        <!--false＝チェックしていない時はデータを送信しない-->
        <!--参考URL＝https://prograshi.com/framework/rails/check_box/-->
        <%= f.check_box :image_ids, {multiple: true, style: 'transform: scale(2);'}, image.id, false  %>
        <%#= f.check_box :image_ids, {:multiple => true}, image.id, false  %>

        <%= image_tag image.variant(resize: "200x200"), class: "pr-3" %>
      <% end %>
    </article>


    <div class="row mt-2">
      <div class="col-2"><label for="design[name]">デザイン名</label></div>
      <div class="col-auto"><%= f.text_field :design_name, autofocus: true, required: true %></div>
    </div>

    <div class="row">
      <div class="col-2"><label for="design[introduction]">デザイン説明</label></div>
      <div class="col-auto"><%= f.text_area :design_introduction, required: true%></div>
    </div>

    <div class="row">
      <div class="col-2"><label for="design[genre_id]">ジャンル</label></div>
      <div class="col-auto"><%= f.collection_select :genre_id, Genre.all, :id, :name, {:include_blank => "ジャンルを選択"},{required: true} %></div>
    </div>

    <div class="row">
      <div class="col-2"><label for="design[price]">税抜価格</label></div>
      <div class="col-auto"><%= f.text_field :design_price, required: true%></div>
    </div>


    <h4 class="mb-3 mt-3 font-weight-bold border-bottom">商品</h4>


    <%= link_to_add_association '＋''商品を追加',
                              # form_withのformタグ変数
                              f,
                              # フォームのデータを追加するモデル名
                              :items, class: 'btn btn-success mb-3',
                              # 追加するフォームの部分テンプレート
                              partial: "item-form-edit",
                              # オプション
                              data: {
                                # フォームを追加する場所の指定
                                association_insertion_node: '#item-forms',
                                # フォームを前後どの位置に追加するか。(初期値: before)
                                association_insertion_method: 'before'
                              },
                              # フォームオブジェクトを指定する場合(初期値 : f)
                              form_name: 'item',
                              # 部分テンプレートに渡す変数があれば記述
                              render_options: {
                                locals: {
                                  # 通常の部分テンプレートと同じ記述
                                }
                              }
  %>

    <div id="item-forms">
      <%= f.fields_for :items do |item| %>
        <%= render partial: 'item-form-edit', locals: {item: item} %>
      <% end %>
    </div>

    <div class="d-flex justify-content-center">
      <%= f.submit '保存', class: "btn btn-sm btn-primary px-4 py-1" %>
      <%= link_to '戻る',admin_design_path(@design.id), class: "btn btn-sm btn-warning text-light px-4 py-1 mx-3" %>
      <%= link_to '削除',admin_design_path, method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-sm btn-danger px-4 py-1" %>
    </div>

  </div>
<% end %>

app/views/admin/designs/index.html.erb
<%= render 'layouts/admin-header' %>
<div class="container">

  <h3 class="mb-3 mt-3">デザイン一覧</h3>

  <table class="table">
    <thead>
      <th>デザインID</th>
      <th></th>
      <th>デザイン名</th>
      <th>ジャンル</th>
      <th>税抜価格</th>
      <th>商品数</th>
      <th>販売停止中</th>
      <th>在庫数０</th>
      <th>レビュー</th>
      <th></th>
    </thead>
    <tbody>
      <% @designs.each do |design| %>
        <tr>
          <td><%= link_to admin_design_path(design.id) do %><%= design.id %><% end %></td>
          <td></td>
          <td><%= design.design_name %></td>
          <td><%= design.genre.name %></td>
          <td><%= design.design_price %></td>
          <td><%= design.items.count %></td>
          <td><%= design.items.where(is_active: false).count %></td>
          <td><%= design.items.where(stock: "0").count %></td>

          <td class="d-flex">
            <%= link_to admin_reviews_path(design_id: design.id) do %>
              <p><%= design.reviews.count %>件</p>
            <% end %>
            <p>(<%= design.reviews.average(:rate).to_f.round(1) %>/5)</p>

              <script>
                  $('#star-rate-<%= design.id %>').raty({
                  size: 36,
                  starOff: "<%= asset_path('star-off.png') %>",
                  starOn: "<%= asset_path('star-on.png') %>",
                  starHalf: "<%= asset_path('star-half.png') %>",
                  half: true,   /*星半分表示*/
                  readOnly: true,   /*読み取り専用*/
                  score: <%= design.reviews.average(:rate).to_f.round(1) %>,   /*星評価の表示*/
                });
              </script>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/designs/new.html.erb
<%= render 'layouts/admin-header' %>

<%= form_with model: @design, url: admin_designs_path, local: true do |f| %>

  <div class="container">

    <h3 class="mb-3 mt-3">デザイン</h3>

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold">商品タイプ</div>
      <%= f.radio_button :design_type, true, checked: true %>
      <%= f.label :design_type, "通常商品", {value: true, style: "display: inline-block;"} %>
      <%= f.radio_button :design_type, false, checked: false %>
      <%= f.label :design_type, "オーダーメイド商品", {value: false, style: "display: inline-block;"} %>
    </div>

    <article>
      <label for="images" class="font-weight-bold">画像追加</label>
      <%= f.file_field :images, accept: "image/*" , required: true, multiple: true %>
      <output id="result" />
    </article>

    <div class="row mt-2">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="design[name]">デザイン名</label></div>
      <div class="col-auto"><%= f.text_field :design_name, autofocus: true, required: true%></div>
    </div>

    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="design[introduction]">デザイン説明</label></div>
      <div class="col-auto"><%= f.text_area :design_introduction, required: true%></div>
    </div>
    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="design[genre_id]">ジャンル</label></div>
      <div class="col-auto"><%= f.collection_select :genre_id, Genre.all, :id, :name, {:include_blank => "ジャンルを選択"},{required: true} %></div>
    </div>
    <div class="row">
      <div class="col-md-2 col-sm-3 font-weight-bold"><label for="design[price]">税抜価格</label></div>
      <div class="col-auto"><%= f.text_field :design_price, required: true%></div>
    </div>



    <h3 class="mb-3 mt-3">商品</h3>

    <!--<button>追加する</button>-->
    <!--<%#= f.fields_for :items do |item| %>-->
    <!--<%# end %>-->

    <%= link_to_add_association '＋''商品を追加',
                              # form_withのformタグ変数
                              f,
                              # フォームのデータを追加するモデル名
                              :items, class: 'btn btn-success mb-3',
                              # 追加するフォームの部分テンプレート
                              partial: "item-form",
                              # オプション
                              data: {
                                # フォームを追加する場所の指定
                                association_insertion_node: '#item-forms',
                                # フォームを前後どの位置に追加するか。(初期値: before)
                                association_insertion_method: 'before'
                              },
                              # フォームオブジェクトを指定する場合(初期値 : f)
                              form_name: 'item',
                              # 部分テンプレートに渡す変数があれば記述
                              render_options: {
                                locals: {
                                  # 通常の部分テンプレートと同じ記述
                                }
                              }
  %>

    <%#= f.fields_for :items do |item| %>
      <%#= render partial: 'item-form', locals: {item: item} %>
    <%# end %>

    <%= f.fields_for :items do |item| %>
      <%= render partial: 'item-form', locals: {item: item} %>
    <% end %>
    <div id="item-forms">
    </div>


    <div class="row mt-5 justify-content-center"><%= f.submit '保存', class: "btn btn-lg btn-primary px-5 py-1" %></div>

  </div>

<% end %>

app/views/admin/designs/show.html.erb
<%= render 'layouts/admin-header' %>

<div class="container">

  <h3 class="mb-3 mt-3">デザイン詳細</h3>

  <h4 class="mb-3 mt-3 font-weight-bold border-bottom-dark">デザイン</h4>
  <div class="row d-flex flex-wrap">
    <% @design.images.each do |image| %>
      <%= image_tag image.variant(resize: "200x200"), class:"pl-3" %>
    <% end %>
  </div>


  <div class="justify-content-center">
    <div>
      <label for="" class="col-lg-2 col-md-3 col-sm-4 col-4 p-0 font-weight-bold">デザイン名</label>
      <%= @design.design_name %>
    </div>
    <div>
      <label for="" class="col-lg-2 col-md-3 col-sm-4 col-4 p-0 font-weight-bold">デザイン説明</label>
      <%= @design.design_introduction %>
    </div>
    <div>
      <label for="" class="col-lg-2 col-md-3 col-sm-4 col-4 p-0 font-weight-bold">ジャンル</label>
      <%= @design.genre.name %>
    </div>
    <div>
      <label for="" class="col-lg-2 col-md-3 col-sm-4 col-4 p-0 font-weight-bold">デザイン価格</label>
      <%= "￥" %><%= @design.design_price.to_s(:delimited) %><%= "～" %>
    </div>
  </div>

  <h4 class="mb-3 mt-3 font-weight-bold border-bottom">商品一覧</h4>
  <div class="row d-flex flex-wrap">
    <% @design.items.each do |item|%>
      <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
        <% if @design.design_type %>
          <%= image_tag item.image.variant(resize: "200x200"), class: "border" %><br>
          <label for="" class="col-lg-6 col-md-6 col-sm-6 col-4 p-0 font-weight-bold">商品ID</label>
          <%= item.id %><br>
          <label for="" class="col-lg-6 col-md-6 col-sm-6 col-4 p-0 font-weight-bold">商品価格(税抜)</label>
          <%= "￥" %><%= item.item_price.to_s(:delimited) %><br>
          <label for="" class="col-lg-6 col-md-6 col-sm-6 col-4 p-0 font-weight-bold">在庫数</label>
          <%= item.stock %><br>
          <label for="" class="col-lg-6 col-md-6 col-sm-6 col-4 p-0 font-weight-bold">販売status</label>
            <%= item.is_active ? '販売中' : '販売停止中' %><br>
          <label for="" class="col-lg-6 col-md-6 col-sm-6 col-4 p-0 font-weight-bold">商品説明</label>
          <%= item.item_introduction %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="col-4">
      <%= link_to "編集する", edit_admin_design_path, class: "btn btn-primary btn-block" %>
    </div>
  </div>

</div>