config/routes.rb
Rails.application.routes.draw do


# 顧客用
# URL /customers/sign_in ...

devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# # 管理者用
# # URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :designs, only: [:new, :create, :show, :edit, :update, :index, :destroy]
    resources :items, only: [:create]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :update]
    resources :orders, only: [:show, :update]
    resources :reviews, only: [:index, :destroy]
    get '/' => 'homes#top'
  end

  root to: "public/homes#top"
  scope module: :public do
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    get '/customers/my_page', to: 'customers#show'
    get '/customers/my_page/edit', to: 'customers#edit'
    patch '/customers/my_page', to: 'customers#update'
    resources :designs, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy, :destroy_all]
    post '/cart_items/order_made_create' => 'cart_items#order_made_create'
    delete :cart_items, to: 'cart_items#destroy_all'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks'=> 'orders#thanks'
    resources :orders, only: [:new, :index, :show, :create]
    resources :reviews, only: [:index, :new, :create]
  end
end


#new_admin_session GET    /admin/sign_in(.:format)                        admin/sessions#new
#admin_session POST   /admin/sign_in(.:format)                            admin/sessions#create
#destroy_admin_session DELETE /admin/sign_out(.:format)                   admin/sessions#destroy

#admin GET    /admin(.:format)                                              admin/homes#top

#admin_designs GET    /admin/designs(.:format)                             admin/designs#index
#              POST   /admin/designs(.:format)                             admin/designs#create
#new_admin_design GET    /admin/designs/new(.:format)                      admin/designs#new
#edit_admin_design GET    /admin/designs/:id/edit(.:format)                admin/designs#edit
#admin_design GET    /admin/designs/:id(.:format)                          admin/designs#show
#             PATCH  /admin/designs/:id(.:format)                          admin/designs#update
#             DELETE /admin/designs/:id(.:format)                          admin/designs#destroy

#admin_items POST   /admin/items(.:format)                                 admin/items#create

#admin_genres GET    /admin/genres(.:format)                                admin/genres#index
#             POST   /admin/genres(.:format)                                admin/genres#create
#edit_admin_genre GET    /admin/genres/:id/edit(.:format)                   admin/genres#edit
#admin_genre PATCH  /admin/genres/:id(.:format)                             admin/genres#update

#admin_customers GET    /admin/customers(.:format)                          admin/customers#index
#edit_admin_customer GET    /admin/customers/:id/edit(.:format)             admin/customers#edit
#admin_customer GET    /admin/customers/:id(.:format)                       admin/customers#show
#               PATCH  /admin/customers/:id(.:format)                       admin/customers#update

#admin_order GET    /admin/orders/:id(.:format)                             admin/orders#show
#PATCH  /admin/orders/:id(.:format)                                         admin/orders#update

#admin_reviews GET    /admin/reviews(.:format)                              admin/reviews#index
#admin_review DELETE /admin/reviews/:id(.:format)                           admin/reviews#destroy


#new_customer_password GET    /customers/password/new(.:format)             devise/passwords#new
#edit_customer_password GET    /customers/password/edit(.:format)           devise/passwords#edit

#new_customer_registration GET    /customers/sign_up(.:format)              public/registrations#new
#edit_customer_registration GET    /customers/edit(.:format)                public/registrations#edit



#new_customer_session GET    /customers/sign_in(.:format)                   public/sessions#new
#customer_session POST   /customers/sign_in(.:format)                       public/sessions#create
#destroy_customer_session DELETE /customers/sign_out(.:format)              public/sessions#destroy

#genres GET    /genres(.:format)                                            public/genres#index

#designs GET    /designs(.:format)                                          public/designs#index
#design GET    /designs/:id(.:format)                                       public/designs#show

#customers_unsubscribe GET    /customers/unsubscribe(.:format)              public/customers#unsubscribe
#customers_my_page GET    /customers/my_page(.:format)                      public/customers#show
#customers_my_page_edit GET    /customers/my_page/edit(.:format)            public/customers#edit
#                       PATCH  /customers/my_page(.:format)                 public/customers#update
#customers_withdraw PATCH  /customers/withdraw(.:format)                    public/customers#withdraw

#cart_items GET    /cart_items(.:format)                                    public/cart_items#index
#           POST   /cart_items(.:format)                                    public/cart_items#create
#cart_items_order_made_create POST   /cart_items/order_made_create(.:format)    public/cart_items#order_made_create

#cart_item PATCH  /cart_items/:id(.:format)                                 public/cart_items#update
#          DELETE /cart_items/:id(.:format)                                 public/cart_items#destroy
#          DELETE /cart_items(.:format)                                     public/cart_items#destroy_all

#orders GET    /orders(.:format)                                            public/orders#index
#POST   /orders(.:format)                                                   public/orders#create
#new_order GET    /orders/new(.:format)                                     public/orders#new
#order GET    /orders/:id(.:format)                                         public/orders#show
#orders_confirm POST   /orders/confirm(.:format)                            public/orders#confirm
#orders_thanks GET    /orders/thanks(.:format)                              public/orders#thanks

#address_index POST   /address(.:format)                                    public/address#create

#reviews GET    /reviews(.:format)                                          public/reviews#index
#        POST   /reviews(.:format)                                          public/reviews#create
#new_review GET    /reviews/new(.:format)                                   public/reviews#new

#new_customer_password GET    /customers/password/new(.:format)             devise/passwords#new
#edit_customer_password GET    /customers/password/edit(.:format)           devise/passwords#edit
#customer_password PATCH  /customers/password(.:format)                     devise/passwords#update
#PUT    /customers/password(.:format)                                       devise/passwords#update
#POST   /customers/password(.:format)                                       devise/passwords#create

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :last_name, presence: true
         validates :first_name, presence: true
         validates :last_name_kana, presence: true
         validates :first_name_kana, presence: true
         validates :postal_code, presence: true
         validates :address, presence: true
         validates :telephone_number, presence: true


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def full_name
    last_name + ' ' + first_name
  end

  def full_name_kana
    last_name_kana + ' ' + first_name_kana
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.order("created_at DESC")
  end


  def show
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.all.order(created_at: :desc)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<%= render 'layouts/admin-header' %>
<div class="container">

  <h3 class="mb-3 mt-3">顧客一覧</h3>

  <table class="table">
    <tr>
      <th>会員ID</th>
      <th>名前</th>
      <th>会員登録日時</th>
      <th>退会ステータス</th>
    </tr>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= link_to admin_customer_path(customer.id) do %><%= customer.id %><% end %></td>
      <td><%= customer.last_name %><%= customer.first_name %></td>
      <td><%= customer.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
      <td><%= customer.is_deleted ? '退会' : '会員'%></td>
    </tr>
    <% end %>
  </table>

</div>

app/views/admin/customers/show.html.erb
<%= render 'layouts/admin-header' %>

<div class="container">

  <h3 class="mb-3 mt-3">顧客詳細</h3>

  <div class="row">
    <div class="col-12">
      <label for="customer_id" class="col-4 col-sm-6 col-md-5 col-lg-5 col-xl-4 col-form-label">会員ID</label>
      <%= @customer.id %></br>

      <label for="customer_name" class="col-4 col-sm-6 col-md-5  col-lg-5 col-xl-4 col-form-label">氏名</label>
      <%= @customer.last_name %><%= "　" %><%= @customer.first_name %></br>

      <label for="customer_hurigana" class="col-4 col-sm-6 col-md-5  col-lg-5 col-xl-4 col-form-label">フリガナ</label>
      <%= @customer.last_name_kana %><%= "　" %><%= @customer.first_name_kana %></br>

      <label for="customer_postal_code" class="col-4 col-sm-6 col-md-5 col-lg-5 col-xl-4 col-form-label">郵便番号</label>
      <%=@customer.postal_code %></br>

      <label for="customer_address" class="col-4 col-sm-6 col-md-5 col-lg-5 col-xl-4 col-form-label">住所</label>
      <%=@customer.address %></br>

      <label for="customer_telephone_number" class="col-4 col-sm-6 col-md-5 col-xl-4 col-lg-5 col-form-label">電話番号</label>
      <%=@customer.telephone_number %></br>

      <label for="customer_email" class="col-4 col-sm-6 col-md-5 col-lg-5 col-xl-4 col-form-label">メールアドレス</label>
      <%=@customer.email %></br>

      <label for="customer_is_deleted" class="col-4 col-sm-6 col-md-5 col-lg-5 col-xl-4 col-form-label">会員ステータス</label>
       <%= @customer.is_deleted ? '退会' : '有効' %></br>

      <label class="col-1 col-sm-3 col-md-5 col-lg-5 col-xl-4 col-form-label"></label>
      <span class="mr-1">
      </span>
    </div>
  </div>

  <h4 class="mb-3 mt-3 font-weight-bold border-bottom"><%= @customer.full_name %>様 注文履歴一覧</h4>

  <div class="row">
    <div class="col-12">
      <table class="table table-bordered bg-white">
        <thead>
          <tr>
            <th>注文日</th>
            <th>配送先</th>
            <th>注文商品</th>
            <th>支払金額</th>
            <th>製作状況</th>
            <th>注文詳細</th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td class="align-middle"><%= order.created_at.strftime('%Y/%m/%d') %></td>
              <td class="align-middle">
                <%= order.postal_code %><br>
                <%= order.address %><br>
                <%= order.name %>
              </td>

              <td class="align-middle"><% order.order_details.each do |order_detail| %>
                <%= image_tag order_detail.item.image.variant(resize: "100x100") %><%= order_detail.item.design.design_name %><br>
                <% end %>
              </td>

              <td class="align-middle"><%= order.total_price %><%= "円" %></td>
              <td class="align-middle"><%= order.making_status_i18n %></td>
              <td class="align-middle"><%= link_to "表示する", admin_order_path(order.id), class: "btn btn-primary text-light" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>