config/routes.rb
Rails.application.routes.draw do


# 顧客用
# URL /customers/sign_in ...

devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# # 管理者用
# # URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :designs, only: [:new, :create, :show, :edit, :update, :index, :destroy]
    resources :items, only: [:create]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :update]
    resources :orders, only: [:show, :update]
    resources :reviews, only: [:index, :destroy]
    get '/' => 'homes#top'
  end

  root to: "public/homes#top"
  scope module: :public do
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    get '/customers/my_page', to: 'customers#show'
    get '/customers/my_page/edit', to: 'customers#edit'
    patch '/customers/my_page', to: 'customers#update'
    resources :designs, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy, :destroy_all]
    post '/cart_items/order_made_create' => 'cart_items#order_made_create'
    delete :cart_items, to: 'cart_items#destroy_all'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks'=> 'orders#thanks'
    resources :orders, only: [:new, :index, :show, :create]
    resources :reviews, only: [:index, :new, :create]
  end
end


#new_admin_session GET    /admin/sign_in(.:format)                        admin/sessions#new
#admin_session POST   /admin/sign_in(.:format)                            admin/sessions#create
#destroy_admin_session DELETE /admin/sign_out(.:format)                   admin/sessions#destroy

#admin GET    /admin(.:format)                                              admin/homes#top

#admin_designs GET    /admin/designs(.:format)                             admin/designs#index
#              POST   /admin/designs(.:format)                             admin/designs#create
#new_admin_design GET    /admin/designs/new(.:format)                      admin/designs#new
#edit_admin_design GET    /admin/designs/:id/edit(.:format)                admin/designs#edit
#admin_design GET    /admin/designs/:id(.:format)                          admin/designs#show
#             PATCH  /admin/designs/:id(.:format)                          admin/designs#update
#             DELETE /admin/designs/:id(.:format)                          admin/designs#destroy

#admin_items POST   /admin/items(.:format)                                 admin/items#create

#admin_genres GET    /admin/genres(.:format)                                admin/genres#index
#             POST   /admin/genres(.:format)                                admin/genres#create
#edit_admin_genre GET    /admin/genres/:id/edit(.:format)                   admin/genres#edit
#admin_genre PATCH  /admin/genres/:id(.:format)                             admin/genres#update

#admin_customers GET    /admin/customers(.:format)                          admin/customers#index
#edit_admin_customer GET    /admin/customers/:id/edit(.:format)             admin/customers#edit
#admin_customer GET    /admin/customers/:id(.:format)                       admin/customers#show
#               PATCH  /admin/customers/:id(.:format)                       admin/customers#update

#admin_order GET    /admin/orders/:id(.:format)                             admin/orders#show
#PATCH  /admin/orders/:id(.:format)                                         admin/orders#update

#admin_reviews GET    /admin/reviews(.:format)                              admin/reviews#index
#admin_review DELETE /admin/reviews/:id(.:format)                           admin/reviews#destroy


#new_customer_password GET    /customers/password/new(.:format)             devise/passwords#new
#edit_customer_password GET    /customers/password/edit(.:format)           devise/passwords#edit

#new_customer_registration GET    /customers/sign_up(.:format)              public/registrations#new
#edit_customer_registration GET    /customers/edit(.:format)                public/registrations#edit



#new_customer_session GET    /customers/sign_in(.:format)                   public/sessions#new
#customer_session POST   /customers/sign_in(.:format)                       public/sessions#create
#destroy_customer_session DELETE /customers/sign_out(.:format)              public/sessions#destroy

#genres GET    /genres(.:format)                                            public/genres#index

#designs GET    /designs(.:format)                                          public/designs#index
#design GET    /designs/:id(.:format)                                       public/designs#show

#customers_unsubscribe GET    /customers/unsubscribe(.:format)              public/customers#unsubscribe
#customers_my_page GET    /customers/my_page(.:format)                      public/customers#show
#customers_my_page_edit GET    /customers/my_page/edit(.:format)            public/customers#edit
#                       PATCH  /customers/my_page(.:format)                 public/customers#update
#customers_withdraw PATCH  /customers/withdraw(.:format)                    public/customers#withdraw

#cart_items GET    /cart_items(.:format)                                    public/cart_items#index
#           POST   /cart_items(.:format)                                    public/cart_items#create
#cart_items_order_made_create POST   /cart_items/order_made_create(.:format)    public/cart_items#order_made_create

#cart_item PATCH  /cart_items/:id(.:format)                                 public/cart_items#update
#          DELETE /cart_items/:id(.:format)                                 public/cart_items#destroy
#          DELETE /cart_items(.:format)                                     public/cart_items#destroy_all

#orders GET    /orders(.:format)                                            public/orders#index
#POST   /orders(.:format)                                                   public/orders#create
#new_order GET    /orders/new(.:format)                                     public/orders#new
#order GET    /orders/:id(.:format)                                         public/orders#show
#orders_confirm POST   /orders/confirm(.:format)                            public/orders#confirm
#orders_thanks GET    /orders/thanks(.:format)                              public/orders#thanks

#address_index POST   /address(.:format)                                    public/address#create

#reviews GET    /reviews(.:format)                                          public/reviews#index
#        POST   /reviews(.:format)                                          public/reviews#create
#new_review GET    /reviews/new(.:format)                                   public/reviews#new

#new_customer_password GET    /customers/password/new(.:format)             devise/passwords#new
#edit_customer_password GET    /customers/password/edit(.:format)           devise/passwords#edit
#customer_password PATCH  /customers/password(.:format)                     devise/passwords#update
#PUT    /customers/password(.:format)                                       devise/passwords#update
#POST   /customers/password(.:format)                                       devise/passwords#create

app/views/layouts/_admin-header.html.erb
<% if admin_signed_in? %>

  <div class="row justify-content-center bg-dark">
    <h2 class="m-4 p-2 text-light">管理者画面</h2>
  </div>
  <div class="row justify-content-center bg-success">
    <%= link_to "ジャンル一覧", admin_genres_path, class: "text-light ml-5 p-2" %>
    <%= link_to "商品一覧", admin_designs_path, class: "text-light ml-5 p-2" %>
    <%= link_to "商品追加", new_admin_design_path, class: "text-light ml-5 p-2" %>
    <%= link_to "顧客一覧", admin_customers_path, class: "text-light ml-5 p-2" %>
    <%= link_to "注文一覧", admin_path, class: "text-light ml-5 p-2" %>
    <%= link_to destroy_admin_session_path, method: :delete, class: "text-light ml-5 p-2" do %>管理者ログアウト<% end %>
  </div>

<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="background">

    <div class="footer-text-kana">hanahiroba</div>
    <p class="footer-text"><%= link_to "花広場", root_path %></p>

    <div class="footer-center">
      <a href="https://tsumami-j.com/">つまみ細工協会HP</a>
      <a href="https://instagram.com/murakana131?igshid=YmMyMTA2M2Y=">
        instagram<i class="fa-brands fa-square-instagram"></i>
      </a>
    </div>
    <p class="copyright">Copyright © ZORO 2022</p>

  </div>
</footer>

app/views/layouts/_header.html.erb
  <header>
    <div class="header-background">
      <div class="header-sakura">
        <div class="nav-hanahiroba-icon"></div>
        <div class="nav-text">
          <li>ジャンルで選ぶ</li>
          <% genre.each do |genre| %>
            <%= link_to designs_path(genre_id: genre.id), class: "path" do %><li class="nav-genre">&emsp;--<%= genre.name %></li><% end %>
          <% end %>
          <%= link_to designs_path, class: "path" do %><li class="nav-name">すべての商品</li><% end %>
          <%= link_to cart_items_path, class: "path" do %><li class="nav-name">カート</li><% end %>
          <% if customer_signed_in? %>
            <%= link_to customers_my_page_path, class: "path" do %><li class="nav-name">マイページ</li><% end %>
            <%= link_to destroy_customer_session_path, method: :delete, class: "path" do %><li class="nav-name">ログアウト</li><% end %>
          <% else %>
            <%= link_to new_customer_session_path, class: "path" do %><li class="nav-name">ログイン</li><% end %>
            <%= link_to new_customer_registration_path, class: "path" do %><li class="nav-name">会員登録</li><% end %>
          <% end %>
        </div>
        <div class="login-content">
          <% if customer_signed_in? %>
            <p>◆<%= current_customer.last_name %>さんログイン中</p>
            <!--<p>ログイン中</p>-->
          <% else %>
            <p><%= flash[:notice] %></p>
          <% end %>
        </div>
      </div>
    </div>
  </header>




<!--ハンバーガーアイコン-->
<div class="public-sidebar">
  <div class="public-hanahiroba-icon"></div>
  <div id="public-hm-icon">
    <a class="menu-trigger" href="#">
      <span></span>
      <span>menu</span>
      <span></span>
    </a>
  </div>
</div>




<div id="sp-menu">
  <ul class="menu-content">
    <% genre.each do |genre| %>
      <%= link_to designs_path(genre_id: genre.id), class: "path_line" do %><li class="nav-genre"><%= genre.name %></li><% end %>
    <% end %>

    <%= link_to designs_path, class: "path_line" do %><li>すべての商品</li><% end %>
    <%= link_to cart_items_path, class: "path_line" do %><li>カート</li><% end %>
    <% if customer_signed_in?%>
      <%= link_to customers_my_page_path, class: "path_line" do %><li>マイページ</li><% end %>
      <%= link_to destroy_customer_session_path, method: :delete, class: "path_line" do %><li>ログアウト</li><% end %>
    <% else %>
      <%= link_to new_customer_session_path, class: "path_line" do %><li>ログイン</li><% end %>
      <%= link_to new_customer_registration_path, class: "path_line" do %><li>会員登録</li><% end %>
    <% end %>
  </ul>
</div>




<script>
  // $(document).ready(function () {
  //   particlesJS(".header-background", {
  //   	"particles":{
  //   		"number":{
  //   			"value":30,//この数値を変更すると桜の数が増減できる
  //   			"density":{
  //   				"enable":true,
  //   				"value_area":1121.6780303333778
  //   			}
  //   		},
  //   		"color":{
  //   			"value":"#fff"
  //   		},
  //   		"shape":{
  //   			"type":"image",//形状は画像を指定
  //   			"stroke":{
  //   				"width":0,
  //   			},
  //   			"image":{
  //   				"src":"icon49_5.png",//【重要】画像を指定！桜の画像を設定してください。
  //   				"width":120,
  //   				"height":120
  //   			}
  //   		},
  //   		"opacity":{
  //   			"value":0.06409588744762158,
  //   			"random":true,
  //   			"anim":{
  //   				"enable":false,
  //   				"speed":1,
  //   				"opacity_min":0.1,
  //   				"sync":false
  //   			}
  //   		},
  //   		"size":{
  //   			"value":8.011985930952697,
  //   			"random":true,//サイズをランダムに
  //   			"anim":{
  //   				"enable":false,
  //   				"speed":4,
  //   				"size_min":0.1,
  //   				"sync":false
  //   			}
  //   		},
  //   		"line_linked":{
  //   			"enable":false,
  //   		},
  //   		"move":{
  //   			"enable":true,
  //   			"speed":7,//この数値を小さくするとゆっくりな動きになる
  //   			"direction":"bottom-right",//右下に向かって落ちる
  //   			"random":false,//動きはランダムにしない
  //   			"straight":false,//動きをとどめない
  //   			"out_mode":"out",//画面の外に出るように描写
  //   			"bounce":false,//跳ね返りなし
  //   			"attract":{
  //   				"enable":false,
  //   				"rotateX":281.9177489524316,
  //   				"rotateY":127.670995809726
  //   			}
  //   		}
  //   	},
  //   	"interactivity":{
  //   		"detect_on":"canvas",
  //   		"events":{
  //   			"onhover":{
  //   				"enable":false,
  //   			},
  //   			"onclick":{
  //   				"enable":false,
  //   			},
  //   			"resize":true
  //   		}
  //   	},
  //   	"retina_detect":false
  //   });
  // });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hanahiroba</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <script src="https://kit.fontawesome.com/c3b216bb73.js" crossorigin="anonymous"></script>



    <style>
      .body {
        font-size: calc(min(1.5vw,16px));
      }
      .container {
        font-size: calc(min(1.5vw,16px));
      }
    </style>
    <!--slick導入-->
    <!--<link rel="stylesheet" type="text/css" href="css/slick.css"/>-->
    <!--<link rel="stylesheet" type="text/css" href="css/slick-theme.css"/>-->


    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <!--swiper CDN-->
    <!--<script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>-->


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sawarabi+Mincho&family=Zen+Antique&family=Zen+Old+Mincho&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Opti:wght@700&family=Kaisei+Tokumin:wght@800&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Opti:wght@700&family=Kaisei+Tokumin:wght@800&family=Yuji+Syuku&display=swap" rel="stylesheet">

    <!--swiper CDN-->
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>-->

  </head>

  <body>
    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>

</html>